package Homepage;

/*Generated by MPS */

import com.mbeddr.mpsutil.projectview.runtime.IProjectViewDescriptor;
import java.util.List;
import com.mbeddr.mpsutil.projectview.runtime.IViewDescriptor;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class ProjectViewDescriptor implements IProjectViewDescriptor {
  public static ProjectViewDescriptor INSTANCE = new ProjectViewDescriptor();

  private List<IViewDescriptor> myViews = ListSequence.fromList(new ArrayList<IViewDescriptor>());

  public ProjectViewDescriptor() {
  }

  @Override
  public Iterable<IViewDescriptor> getViewDescriptors() {
    return myViews;
  }
}
