package homepage_lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptFolder = createDescriptorForFolder();
  /*package*/ final ConceptDescriptor myConceptHTML_IContent = createDescriptorForHTML_IContent();
  /*package*/ final ConceptDescriptor myConceptHTML_div = createDescriptorForHTML_div();
  /*package*/ final ConceptDescriptor myConceptHTML_h2 = createDescriptorForHTML_h2();
  /*package*/ final ConceptDescriptor myConceptHTML_h3 = createDescriptorForHTML_h3();
  /*package*/ final ConceptDescriptor myConceptHTML_href = createDescriptorForHTML_href();
  /*package*/ final ConceptDescriptor myConceptHTML_img = createDescriptorForHTML_img();
  /*package*/ final ConceptDescriptor myConceptHTML_li = createDescriptorForHTML_li();
  /*package*/ final ConceptDescriptor myConceptHTML_p = createDescriptorForHTML_p();
  /*package*/ final ConceptDescriptor myConceptHTML_ul = createDescriptorForHTML_ul();
  /*package*/ final ConceptDescriptor myConceptHomepage = createDescriptorForHomepage();
  /*package*/ final ConceptDescriptor myConceptILink = createDescriptorForILink();
  /*package*/ final ConceptDescriptor myConceptLinkToPage = createDescriptorForLinkToPage();
  /*package*/ final ConceptDescriptor myConceptLinkToWebAddress = createDescriptorForLinkToWebAddress();
  /*package*/ final ConceptDescriptor myConceptMetaInfo = createDescriptorForMetaInfo();
  /*package*/ final ConceptDescriptor myConceptPage = createDescriptorForPage();
  /*package*/ final ConceptDescriptor myConceptstrong = createDescriptorForstrong();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0x92d2ea165a424fdfL, 0xa676c7604efe3504L, "de.slisson.mps.richtext");
    deps.aggregatedLanguage(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, "file_system");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptFolder, myConceptHTML_IContent, myConceptHTML_div, myConceptHTML_h2, myConceptHTML_h3, myConceptHTML_href, myConceptHTML_img, myConceptHTML_li, myConceptHTML_p, myConceptHTML_ul, myConceptHomepage, myConceptILink, myConceptLinkToPage, myConceptLinkToWebAddress, myConceptMetaInfo, myConceptPage, myConceptstrong);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Folder:
        return myConceptFolder;
      case LanguageConceptSwitch.HTML_IContent:
        return myConceptHTML_IContent;
      case LanguageConceptSwitch.HTML_div:
        return myConceptHTML_div;
      case LanguageConceptSwitch.HTML_h2:
        return myConceptHTML_h2;
      case LanguageConceptSwitch.HTML_h3:
        return myConceptHTML_h3;
      case LanguageConceptSwitch.HTML_href:
        return myConceptHTML_href;
      case LanguageConceptSwitch.HTML_img:
        return myConceptHTML_img;
      case LanguageConceptSwitch.HTML_li:
        return myConceptHTML_li;
      case LanguageConceptSwitch.HTML_p:
        return myConceptHTML_p;
      case LanguageConceptSwitch.HTML_ul:
        return myConceptHTML_ul;
      case LanguageConceptSwitch.Homepage:
        return myConceptHomepage;
      case LanguageConceptSwitch.ILink:
        return myConceptILink;
      case LanguageConceptSwitch.LinkToPage:
        return myConceptLinkToPage;
      case LanguageConceptSwitch.LinkToWebAddress:
        return myConceptLinkToWebAddress;
      case LanguageConceptSwitch.MetaInfo:
        return myConceptMetaInfo;
      case LanguageConceptSwitch.Page:
        return myConceptPage;
      case LanguageConceptSwitch.strong:
        return myConceptstrong;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForFolder() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "Folder", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x14db63a52955ffb8L);
    b.class_(false, false, true);
    b.parent(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52955d10aL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/1502904461672447928");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML_IContent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "HTML_IContent", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL);
    b.interface_();
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/798157908154122558");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML_div() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "HTML_div", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32b5ccL);
    b.class_(false, false, false);
    b.parent(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/798157908154168780");
    b.version(2);
    b.aggregate("contents", 0xb13a0637e32b5cdL).target(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL).optional(true).ordered(true).multiple(true).origin("798157908154168781").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML_h2() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "HTML_h2", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e3188e8L);
    b.class_(false, false, false);
    b.parent(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/798157908154091752");
    b.version(2);
    b.property("content", 0xb13a0637e3188e9L).type(PrimitiveTypeId.STRING).origin("798157908154091753").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML_h3() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "HTML_h3", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e33f6dbL);
    b.class_(false, false, false);
    b.parent(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/798157908154250971");
    b.version(2);
    b.property("content", 0xb13a0637e33f6ddL).type(PrimitiveTypeId.STRING).origin("798157908154250973").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML_href() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "HTML_href", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x354ee16775aa6e17L);
    b.class_(false, false, false);
    b.parent(0x92d2ea165a424fdfL, 0xa676c7604efe3504L, 0x237c8da86a9e7aecL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/3841255366665596439");
    b.version(2);
    b.property("text", 0x354ee16775aa6e18L).type(PrimitiveTypeId.STRING).origin("3841255366665596440").done();
    b.aggregate("target", 0x68dbe8e7eb2dd1bdL).target(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x14db63a52947c3cfL).optional(false).ordered(true).multiple(false).origin("7555888882624876989").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML_img() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "HTML_img", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x7320a3ba62fab23fL);
    b.class_(false, false, false);
    b.parent(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/8295810534536294975");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML_li() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "HTML_li", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e36bd11L);
    b.class_(false, false, false);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/798157908154432785");
    b.version(2);
    b.aggregate("content", 0xb13a0637e36bd16L).target(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL).optional(false).ordered(true).multiple(false).origin("798157908154432790").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML_p() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "HTML_p", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x354ee16775a697acL);
    b.class_(false, false, false);
    b.parent(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/3841255366665344940");
    b.version(2);
    b.aggregate("content", 0x354ee16775a697afL).target(0x92d2ea165a424fdfL, 0xa676c7604efe3504L, 0x237c8da86a9e4e61L).optional(false).ordered(true).multiple(false).origin("3841255366665344943").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHTML_ul() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "HTML_ul", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e361afeL);
    b.class_(false, false, false);
    b.parent(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/798157908154391294");
    b.version(2);
    b.aggregate("contents", 0xb13a0637e361b00L).target(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e36bd11L).optional(false).ordered(true).multiple(true).origin("798157908154391296").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHomepage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "Homepage", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x7320a3ba6306c90bL);
    b.class_(false, false, true);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/8295810534537087243");
    b.version(2);
    b.property("ftp_address", 0x7320a3ba630ac642L).type(PrimitiveTypeId.STRING).origin("8295810534537348674").done();
    b.property("ftp_user", 0x7320a3ba630ac644L).type(PrimitiveTypeId.STRING).origin("8295810534537348676").done();
    b.property("ftp_password", 0x7320a3ba630ac647L).type(PrimitiveTypeId.STRING).origin("8295810534537348679").done();
    b.aggregate("root_folder", 0x7320a3ba6306c90cL).target(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x14db63a52955ffb8L).optional(false).ordered(true).multiple(false).origin("8295810534537087244").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForILink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "ILink", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x14db63a52947c3cfL);
    b.interface_();
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/1502904461671515087");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLinkToPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "LinkToPage", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x14db63a52948445aL);
    b.class_(false, false, false);
    b.parent(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x14db63a52947c3cfL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/1502904461671547994");
    b.version(2);
    b.aggregate("target", 0x14db63a529484460L).target(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7c4L).optional(false).ordered(true).multiple(false).origin("1502904461671548000").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLinkToWebAddress() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "LinkToWebAddress", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x14db63a52948445cL);
    b.class_(false, false, false);
    b.parent(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x14db63a52947c3cfL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/1502904461671547996");
    b.version(2);
    b.property("address", 0x14db63a529484461L).type(PrimitiveTypeId.STRING).origin("1502904461671548001").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMetaInfo() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "MetaInfo", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x6c1d237276aa0e73L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/7790421904944926323");
    b.version(2);
    b.property("content", 0x6c1d237276aa0e76L).type(PrimitiveTypeId.STRING).origin("7790421904944926326").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "Page", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x6c1d237276aa0e6dL);
    b.class_(false, false, true);
    b.parent(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7ceL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/7790421904944926317");
    b.version(2);
    b.property("header_title", 0x6c1d237276aa0e7bL).type(PrimitiveTypeId.STRING).origin("7790421904944926331").done();
    b.aggregate("meta", 0x6c1d237276aa0e78L).target(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x6c1d237276aa0e73L).optional(true).ordered(true).multiple(true).origin("7790421904944926328").done();
    b.aggregate("navlinks", 0x777ce919aa6e463aL).target(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x354ee16775aa6e17L).optional(true).ordered(true).multiple(true).origin("8610012884068353594").done();
    b.aggregate("content", 0xb13a0637e3188e7L).target(0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0xb13a0637e32013eL).optional(true).ordered(true).multiple(true).origin("798157908154091751").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForstrong() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("homepage_lang", "strong", 0xbdbdd5ad46cd46f4L, 0x9c3602284b29d9f3L, 0x354ee16775a937a2L);
    b.class_(false, false, false);
    b.parent(0x92d2ea165a424fdfL, 0xa676c7604efe3504L, 0x237c8da86a9e7aecL);
    b.origin("r:37a51c15-54fd-4dbe-83b8-2842f007aa21(homepage_lang.structure)/3841255366665516962");
    b.version(2);
    b.property("content", 0x354ee16775a97355L).type(PrimitiveTypeId.STRING).origin("3841255366665532245").done();
    return b.create();
  }
}
