package file_system.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int File = 0;
  public static final int IFileSystemEntry = 1;
  public static final int IFolder = 2;
  public static final int ILink = 3;
  public static final int LinkInFolder = 4;
  public static final int LinkToFile = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L);
    builder.put(0x14db63a52947b7ceL, File);
    builder.put(0x7320a3ba62f3fb5cL, IFileSystemEntry);
    builder.put(0x14db63a52955d10aL, IFolder);
    builder.put(0x14db63a52947b7c0L, ILink);
    builder.put(0x14db63a52947b7c4L, LinkInFolder);
    builder.put(0x14db63a52947b7c1L, LinkToFile);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
