package file_system.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptFile = createDescriptorForFile();
  /*package*/ final ConceptDescriptor myConceptIFileSystemEntry = createDescriptorForIFileSystemEntry();
  /*package*/ final ConceptDescriptor myConceptIFolder = createDescriptorForIFolder();
  /*package*/ final ConceptDescriptor myConceptILink = createDescriptorForILink();
  /*package*/ final ConceptDescriptor myConceptLinkInFolder = createDescriptorForLinkInFolder();
  /*package*/ final ConceptDescriptor myConceptLinkToFile = createDescriptorForLinkToFile();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptFile, myConceptIFileSystemEntry, myConceptIFolder, myConceptILink, myConceptLinkInFolder, myConceptLinkToFile);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.File:
        return myConceptFile;
      case LanguageConceptSwitch.IFileSystemEntry:
        return myConceptIFileSystemEntry;
      case LanguageConceptSwitch.IFolder:
        return myConceptIFolder;
      case LanguageConceptSwitch.ILink:
        return myConceptILink;
      case LanguageConceptSwitch.LinkInFolder:
        return myConceptLinkInFolder;
      case LanguageConceptSwitch.LinkToFile:
        return myConceptLinkToFile;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForFile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("file_system", "File", 0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7ceL);
    b.interface_();
    b.parent(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x7320a3ba62f3fb5cL);
    b.origin("r:fa3a44b5-b9bd-4e5d-a3fd-dbf555d6d56d(file_system.structure)/1502904461671512014");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIFileSystemEntry() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("file_system", "IFileSystemEntry", 0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x7320a3ba62f3fb5cL);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fa3a44b5-b9bd-4e5d-a3fd-dbf555d6d56d(file_system.structure)/8295810534535854940");
    b.version(2);
    b.property("filename", 0x14db63a529532c31L).type(PrimitiveTypeId.STRING).origin("1502904461672262705").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIFolder() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("file_system", "IFolder", 0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52955d10aL);
    b.interface_();
    b.parent(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x7320a3ba62f3fb5cL);
    b.origin("r:fa3a44b5-b9bd-4e5d-a3fd-dbf555d6d56d(file_system.structure)/1502904461672435978");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForILink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("file_system", "ILink", 0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7c0L);
    b.interface_();
    b.origin("r:fa3a44b5-b9bd-4e5d-a3fd-dbf555d6d56d(file_system.structure)/1502904461671512000");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLinkInFolder() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("file_system", "LinkInFolder", 0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7c4L);
    b.class_(false, false, true);
    b.parent(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7c0L);
    b.origin("r:fa3a44b5-b9bd-4e5d-a3fd-dbf555d6d56d(file_system.structure)/1502904461671512004");
    b.version(2);
    b.associate("folder", 0x14db63a52947b7c7L).target(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52955d10aL).optional(false).origin("1502904461671512007").done();
    b.aggregate("target", 0x14db63a5294ce2b8L).target(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7c0L).optional(false).ordered(true).multiple(false).origin("1502904461671850680").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLinkToFile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("file_system", "LinkToFile", 0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7c1L);
    b.class_(false, false, false);
    b.parent(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7c0L);
    b.origin("r:fa3a44b5-b9bd-4e5d-a3fd-dbf555d6d56d(file_system.structure)/1502904461671512001");
    b.version(2);
    b.associate("target", 0x14db63a52947b7ccL).target(0xe31ee8a970df4859L, 0x9a78d7d9637e5e93L, 0x14db63a52947b7ceL).optional(false).origin("1502904461671512012").done();
    return b.create();
  }
}
